name: Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Compose
      run: |
        docker-compose up -d

    - name: Run tests
      run: |
        pytest -vv --disable-warnings

    - name: Check test results
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Exiting..."
          exit 1
        fi
